insert into School(Name) values ('СЗШ1');
insert into School(Name) values ('СЗШ2');
insert into School(Name) values ('СЗШ3');
insert into School(Name) values ('СЗШ4');
insert into School(Name) values ('СЗШ5');
insert into School(Name) values ('СЗШ6');
insert into School(Name) values ('СЗШ7');
insert into School(Name) values ('СЗШ8');
insert into School(Name) values ('СЗШ9');